---

spring:
#  datasource:
#    uri: ${vcap.services.apikey-pgsql.credentials.uri}
#    url: ${vcap.servicesrvices.apikey-pgsql.credentials.jdbcUrl}
#    username: ${vcap.services.apikey-pgsql.credentials.username}
#    password: ${vcap.services.apikey-pgsql.credentials.password}

  flyway:
    baseline-on-migrate: true