---

server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database: POSTGRESQL

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/europeana
    username: europeana
    password: culture

flyway:
  baseline-on-migrate: true